<template>
  <div id="alg">
    <CommonTop :top-items="topItems"></CommonTop>
    <div class="stxt">
      <span class="ko">
        AI 시장 예측력 & 퀀트의 종목 선별 을 통한 <br>알고리즘 간 시너지 도모
      </span>
      <span class="en">
        AI Market Prediction & Quant's Stock Picking to Create Synergy Between Algorithms
      </span>
    </div>

    <div class="vi">
      <img src="~/assets/image/algorithm.png" alt="" width="100%" class="ko">
      <img src="~/assets/image/axrassi/algorithm.png" alt="" width="100%" class="en">
    </div>

    <div class="bnrList">
      <a href="#"><img src="~/assets/image/axrassi/bnr05.png" alt="" width="85"></a>
      <a href="#"><img src="~/assets/image/axrassi/bnr02.png" alt="" width="80"></a>
      <a href="#"><img src="~/assets/image/axrassi/bnr03.png" alt="" width="88"></a>
      <a href="#"><img src="~/assets/image/axrassi/bnr04.png" alt="" width="90"></a>
    </div>

    <div class="guide_w">
      <div class="guide">
        <strong class="ko">퀀트 알고리즘</strong>
        <strong class="en">Quantitative investment strategies </strong>
        <span class="ko">
          2003년부터 20여년간 지속적인 연구 개발 및 투자 성과
        </span>
        <span class="ko">
          기본 알고리즘의 성과를 바탕으로 자문사 및 일임사 맞춤형 투자 알고리즘 개발 및 제공
        </span>
        <span class="ko">
          증권사 로보마켓 서비스로 현재 운영 중
        </span>
        <span class="en">
          20 years of continuous R&D and investment since 2003 <br>
          Develop and deliver customized investment algorithms to advisors and firms based on the performance of the base algorithm
        </span>
      </div>

      <div class="guide">
        <strong class="ko">AI 알고리즘</strong>
        <strong class="en">AI Investment Strategies </strong>
        <span class="ko">
          2023년 12월 기준, 매수 9개 매도 15개의 독립적인 AI알고리즘으로 종목별 매매 타이밍 생성
        </span>
        <span class="ko">
          변동성을 중심으로 학습된 개별 알고리즘은 지속적인 AI 학습을 통해 스스로 발전 중
        </span>
        <span class="en">
          As of December 2023, 9 buys and 19 sells were generated by 19 independent AI algorithms. Each algorithm is trained around volatility and is continually improving through AI learning.
        </span>
      </div>
    </div>
  </div>

</template>
<script>
import CommonTop from '@/components/CommonTop.vue'

export default {
  components: {
    CommonTop
  },
  data() {
    return {
      topItems: {
        sm: 'AI',
        ko: '알고리즘협업',
        en: 'ThinkPool AI Algorithms'
      }
    }
  }
}
</script>

<style>
#alg{
  @apply bg-[#EFF2FB] px-5
}
#alg > .top{
  @apply pb-10
}
#alg > .top span{
  @apply text-center
}
#alg .stxt{
  @apply w-full text-center text-[14px] text-[#444] leading-5 pb-[35px]
}
.bnrList{
  @apply pt-10 flex flex-wrap gap-2
}
.bnrList a{
  @apply rounded-[6px] w-[156px] h-[45px] overflow-hidden border-[1px] border-[#f0f0f0] flex justify-center items-center bg-white
}
.guide_w{
  @apply flex flex-col w-full gap-[35px] pt-[45px] pb-[70px]
}
.guide{
  @apply flex flex-col w-full gap-2
}
.guide strong{
  @apply text-[16px] text-[#141414] before:content-['\25CF'] before:text-[#5368ff] before:text-[12px] flex gap-[6px] items-center
}
.guide span{
 @apply text-[14px] text-[#141414] tracking-[-0.154px] leading-[18px]
}

</style>
